#! /usr/bin/env bash

project_name=$1



if [ -e $1 ];
 then
   echo "Il y a déjà un répertoire à ce nom"
   exit -1
 fi
mkdir $1
cd $1
echo "# $1">readme.md

mkdir test
touch test/main.cpp
mkdir src

echo "project($1)" >CMakeLists.txt
echo "CMakeLists.txt.user"> .gitignore

git init
git add -A
git commit -m "init (using new_module_cpp)"
